# -*- coding: utf-8 -*-
"""chatbot-ai-gratis-intelligo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvbrEYZnACCf8-w0IPh9E_TOfg8sILuD
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Data Q&A
qa_data = [
    {"question": "Apa itu Intelligo ID?", "answer": "Intelligo ID adalah platform pembelajaran data science dan AI."},
    {"question": "Bagaimana cara mendaftar bootcamp?", "answer": "Anda bisa mendaftar melalui website resmi kami di https://intelligo.id"},
    {"question": "Berapa lama durasi bootcamp?", "answer": "Durasi bootcamp biasanya 4 bulan dengan total 25-30 pertemuan."},
    {"question": "Apakah ada sertifikat setelah selesai bootcamp?", "answer": "Ya, setiap peserta yang lulus akan mendapatkan sertifikat resmi."},
    {"question": "Apakah ada pembimbing untuk setiap peserta?", "answer": "Ya, setiap peserta akan mendapatkan mentor selama bootcamp."},
    {"question": "Bagaimana jika saya ketinggalan kelas?", "answer": "Anda bisa mengakses rekaman kelas melalui LMS Mayar."},
    {"question": "Apakah bootcamp ini untuk pemula?", "answer": "Ya, bootcamp ini dirancang untuk pemula yang ingin belajar data science dan AI."},
    {"question": "Apakah saya perlu background IT untuk ikut bootcamp ini?", "answer": "Tidak perlu, bootcamp ini dirancang untuk peserta dari berbagai latar belakang."},
    {"question": "Bagaimana cara menghubungi customer support?", "answer": "Anda bisa menghubungi kami melalui email atau WhatsApp yang tertera di website."},
    {"question": "Apakah ada program cicilan untuk biaya bootcamp?", "answer": "Ya, kami menyediakan opsi pembayaran cicilan untuk peserta bootcamp."}
]

# Konversi ke dataframe
df_qa = pd.DataFrame(qa_data)

# TF-IDF Vectorizer untuk menghitung kemiripan teks
vectorizer = TfidfVectorizer()
question_vectors = vectorizer.fit_transform(df_qa["question"])

# Fungsi chatbot dengan threshold
def chatbot_response(user_question, threshold=0.3):
    # Transform pertanyaan pengguna ke vektor
    user_vector = vectorizer.transform([user_question])

    # Hitung cosine similarity
    similarity_scores = cosine_similarity(user_vector, question_vectors)

    # Temukan index jawaban dengan similarity tertinggi
    best_match_index = similarity_scores.argmax()
    best_match_score = similarity_scores.max()

    # Logika threshold
    if best_match_score < threshold:
        return "Maaf, saya tidak mengerti pertanyaan Anda. Bisa dijelaskan lebih spesifik?"

    # Return jawaban terbaik
    return df_qa.loc[best_match_index, "answer"]

# Test chatbot
while True:
    user_input = input("Anda: ")
    if user_input.lower() == "exit":
        print("Chatbot: Terima kasih! Sampai jumpa.")
        break
    response = chatbot_response(user_input, threshold=0.3)
    print(f"Chatbot: {response}")

